# Generated by Django 4.2.2 on 2023-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticscompany_has_district',
            name='CostOfOutsource',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
