# Generated by Django 4.2.2 on 2023-06-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_donation_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='ExchangeRate',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
