# Generated by Django 4.2.2 on 2023-06-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_currency_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='ExchangeRate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='logisticscompany_has_district',
            name='CostOfOutsource',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='TransactionCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_has_items',
            name='UnitItemCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
